# Generated by Django 3.1.7 on 2021-09-03 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('SVC', 'SVC'), ('DT', 'DT'), ('XGBOOST', 'XGBOOST'), ('RF', 'RF'), ('NNC', 'NNC')], max_length=50)),
                ('new_model_file_path', models.CharField(max_length=500)),
                ('fitted_model_file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='MlrReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('CSV', 'csv'), ('TXT', 'txt')], max_length=50)),
                ('path', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('mlr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mlrmodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MlrUserRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_user', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='MrlProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('web', models.URLField(blank=True)),
                ('rol', models.ManyToManyField(to='users.MlrUserRol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MlrResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('TEST', 'test'), ('TRAIN', 'train')], max_length=50)),
                ('mlr_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mlrreport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MlrProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_data', models.FileField(blank=True, null=True, upload_to='users/files/%Y/%m/%d/')),
                ('matrix_name', models.CharField(max_length=50)),
                ('attrs_name', models.CharField(max_length=3000)),
                ('class_name', models.CharField(max_length=50)),
                ('test_size', models.FloatField()),
                ('random_state', models.DecimalField(decimal_places=0, max_digits=5)),
                ('sampling_strategy', models.CharField(choices=[('NONE', None)], max_length=20)),
                ('x_train_path', models.CharField(max_length=500)),
                ('y_train_path', models.CharField(max_length=500)),
                ('x_test_path', models.CharField(max_length=500)),
                ('y_test_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mlr_model', models.ManyToManyField(to='users.MlrModel')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MlrParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('mlr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mlrmodel')),
            ],
            options={
                'verbose_name': 'mlr_param',
                'verbose_name_plural': 'mlr_params',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MlrGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('save_path', models.CharField(max_length=1000)),
                ('mlr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mlrmodel')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
