# Generated by Django 3.1.7 on 2021-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mlrgraph_mlrmodel_mlrparams_mlrproject_mlrreport_mlrresult_mlruserrol_mrlprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlrmodel',
            name='params',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='mlrparams',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
